alpha/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('captcha/', include('captcha.urls')),  # 图形验证码功能。要在主项目下添加。
                  path('mdeditor/', include('mdeditor.urls')),  # 为实现markdown功能，不清楚有啥异常
                  re_path(r'^$', include(('login.urls', 'login'), namespace='empty')),      # 命名一定不能重复
                  re_path(r'^login/', include(('login.urls', 'login'), namespace='login')),  # 将路由分发给下面的app处理
                  re_path(r'^home/', include(('home.urls', 'home'), namespace='home')),
                  re_path(r'^post/', include(('post.urls', 'post'), namespace='post')),
                  re_path(r'^main/', include(('main.urls', 'main'), namespace='main')),
                  re_path(r'^introduction/', include(('introduction.urls', 'introduction'), namespace='introduction')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加上这句至关重要，不然照片不显示

if settings.DEBUG:  # 添加媒体文件url,生产环境下使用
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

campus/home/urls.py
from django.urls import path, re_path
from . import views

# 正在部署的应用的名称，Django2.0之后，app的urls.py必须配置app_name，否则会报错。
app_name = 'home'

urlpatterns = [
    re_path('^$', views.empty),  # 正则匹配必须用re_path
    re_path('^center$', views.CenterView.as_view(), name='center'),
    re_path('^center/file$', views.CenterFileView.as_view(), name='file'),
    re_path('^center/link$', views.CenterLinkView.as_view(), name='link'),
    re_path('^center/search/article$', views.SearchArticleView.as_view(), name='search_article'),
    re_path('^center/search/file$', views.SearchFileView.as_view(), name='search_file'),
    re_path('^center/search/link$', views.SearchLinkView.as_view(), name='search_link'),
    re_path('^center/edit/profile/(?P<pk>\d+)$', views.ProfileUpdateView.as_view(), name='profile'),
    re_path('^center/edit/article/(?P<pk>\d+)$', views.ArticleUpdateView.as_view(), name='edit_article'),
    re_path('^center/edit/link/(?P<pk>\d+)$', views.LinkUpdateView.as_view(), name='edit_link'),
    # re_path('^reset', views.reset),
]

campus/main/urls.py
from django.urls import path, re_path
from . import views

# 正在部署的应用的名称，Django2.0之后，app的urls.py必须配置app_name，否则会报错。
app_name = 'main'

urlpatterns = [
    re_path('^$', views.empty),  # 正则匹配必须用re_path
    re_path('^index', views.IndexView.as_view(), name='indexview'),
    re_path('^categories', views.CategoryView.as_view(), name='categoryview'),
    re_path('^articles/(?P<id>.*)', views.ArticleView.as_view(), name='articleview'),
    re_path('^files', views.FileListView.as_view(), name='filelistview'),
    re_path('^links', views.LinkListView.as_view(), name='linklistview'),
    re_path('^search$', views.SearchView.as_view(), name='search'),
    re_path('^filelist/search$', views.SearchFileListView.as_view(), name='searchfilelistview'),
    re_path('^linklist/search$', views.SearchLinkListView.as_view(), name='searchlinklistview'),
    re_path('^visit/(?P<id>.*)/article$', views.VisitArticleView.as_view(), name='visitarticleview'),
    re_path('^visit/(?P<id>.*)/file$', views.VisitFileView.as_view(), name='visitfileview'),
    re_path('^visit/(?P<id>.*)/link$', views.VisitLinkView.as_view(), name='visitlinkview'),
    re_path('^visit/(?P<id>.*)/article/search$', views.VisitSearchArticleView.as_view(), name='visitsearcharticleview'),
    re_path('^visit/(?P<id>.*)/file/search$', views.VisitSearchFileView.as_view(), name='visitsearchfileview'),
    re_path('^visit/(?P<id>.*)/link/search$', views.VisitSearchLinkView.as_view(), name='visitsearchlinkview'),
    re_path('^logout', views.logout, name='logout'),
]

campus/post/urls.py
from django.urls import path, re_path
from . import views

# 正在部署的应用的名称，Django2.0之后，app的urls.py必须配置app_name，否则会报错。
app_name = 'post'

urlpatterns = [
    re_path('^$', views.empty),  # 正则匹配必须用re_path
    re_path('^post', views.post),
    re_path('^article', views.PostArticleView.as_view(), name='article'),
    re_path('^file', views.PostFileView.as_view(), name='file'),
    re_path('^link', views.PostLinkView.as_view(), name='link'),
]

campus/home/models.py
from django.db import models

# Create your models here.

campus/home/forms.py
from django import forms
from login import models as login_models


class ProfileForm(forms.ModelForm):
    class Meta:
        model = login_models.Profile
        fields = ['nickname', 'gender', 'phone', 'portrait', 'resume']

campus/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from . import forms
from django.views.generic import UpdateView
from post import forms as post_forms
from login import models as login_models
from main import models
from main.views import CategoryView


def empty(request):
    return redirect('home:profile')


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class CenterView(CategoryView):
    # 模板位置
    template_name = 'home/center.html'
    model = models.Article

    def get_queryset(self):  # 默认是文章列表视图
        self.articles = self.model.objects.filter(author_id=self.request.user.id)
        page, paginator, page_range = self.get_page(self.articles, 10)
        return locals()

    def get_context_data(self, **kwargs):  # 重写get_context_data方法
        context = super().get_context_data(**kwargs)
        context['item'] = 'Article'
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class CenterFileView(CategoryView):
    # 模板位置
    template_name = 'home/center.html'

    def get_queryset(self):
        my_files = models.File.objects.filter(author_id=self.request.user.id)
        page, paginator, page_range = self.get_page(my_files, 10)
        return locals()

    def get_context_data(self, **kwargs):  # 重写get_context_data方法
        context = super().get_context_data(**kwargs)
        context['item'] = 'File'
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class CenterLinkView(CenterView):
    # 模板位置
    template_name = 'home/center.html'

    def get_queryset(self):
        my_links = models.Link.objects.filter(author_id=self.request.user.id)
        page, paginator, page_range = self.get_page(my_links, 10)
        return locals()

    def get_context_data(self, **kwargs):  # 重写get_context_data方法
        context = super().get_context_data(**kwargs)
        context['item'] = 'Link'
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class SearchArticleView(CenterView):
    template_name = 'home/center.html'

    def get_queryset(self):  # 默认是文章列表视图
        keyword = self.request.GET.get('keyword')
        if keyword:  # 获取搜索的关键词
            self.articles = models.Article.objects.filter(title__icontains=keyword)
        page, paginator, page_range = self.get_page(self.articles, 10)
        return locals()

    def get_context_data(self, **kwargs):  # 重写get_context_data方法
        context = super().get_context_data(**kwargs)
        context['keyword'] = self.get_queryset().get('keyword')
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class SearchFileView(CenterView):
    template_name = 'home/center.html'

    def get_queryset(self):  # 默认是文章列表视图
        my_files = models.File.objects.filter(author_id=self.request.user.id)
        keyword = self.request.GET.get('keyword')
        if keyword:  # 获取搜索的关键词
            my_files = models.File.objects.filter(name__icontains=keyword)
        page, paginator, page_range = self.get_page(my_files, 10)
        return locals()

    def get_context_data(self, **kwargs):  # 重写get_context_data方法
        context = super().get_context_data(**kwargs)
        context['keyword'] = self.get_queryset().get('keyword')
        context['item'] = 'File'
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class SearchLinkView(CenterView):
    template_name = 'home/center.html'

    def get_queryset(self):  # 默认是文章列表视图
        my_links = models.Link.objects.filter(author_id=self.request.user.id)
        keyword = self.request.GET.get('keyword')
        if keyword:  # 获取搜索的关键词
            my_links = models.Link.objects.filter(name__icontains=keyword)
        page, paginator, page_range = self.get_page(my_links, 10)
        return locals()

    def get_context_data(self, **kwargs):  # 重写get_context_data方法
        context = super().get_context_data(**kwargs)
        context['keyword'] = self.get_queryset().get('keyword')
        context['item'] = 'Link'
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class ProfileUpdateView(UpdateView):
    form_class = forms.ProfileForm
    model = login_models.Profile
    template_name = 'home/edit_profile.html'

    def get(self, request, **kwargs):
        self.object = login_models.Profile.objects.get(user_id=self.request.user.id)
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return redirect('home:center')


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class ArticleUpdateView(UpdateView):
    form_class = post_forms.PostArticleForm
    model = models.Article
    template_name = 'home/edit_article.html'

    def get(self, request, **kwargs):
        self.object = super(ArticleUpdateView, self).get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return redirect('home:center')


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class LinkUpdateView(UpdateView):
    form_class = post_forms.PostLinkForm
    model = models.Link
    template_name = 'home/edit_link.html'

    def get(self, request, **kwargs):
        self.object = super(LinkUpdateView, self).get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return redirect('home:center')

templates/home/center.html
{% extends 'main/footer.html' %}
{% load static %}

{% block title %} User center {% endblock title %}

<!---------------------------静态资源----------------------------->

{% block link %}
<link href="{% static 'home/css/center.css' %}" rel="stylesheet"/>
{% endblock link %}

{% block content %}
<div class="container-layne">
    <div class="item item-1">
        <div class="upload">
            <a href="{% url 'home:center' %}">
                <span>Articles</span>&nbsp;<i class="fa fa-file-text" aria-hidden="true"></i>
            </a>
        </div>
        <hr/>
        <div class="upload">
            <a href="{% url 'home:file' %}">
                <span>Files</span>&nbsp;<i class="fa fa-file-archive-o" aria-hidden="true"></i>
            </a>
        </div>
        <hr/>
        <div class="upload">
            <a href="{% url 'home:link' %}">
                <span>Links</span>&nbsp;<i class="fa fa-link" aria-hidden="true"></i>
            </a>
        </div>
        <hr/>
        <div class="upload">
            <span>Change password</span>&nbsp;<i class="fa fa-pencil" aria-hidden="true"></i>
        </div>
        <hr/>
    </div>

    <!---变化的部分--->
    <div class="item item-2 table-responsive">
        <div class="sub-nav">
            <div style="display: inline;float: left;">
                {% if item == 'Article' %}
                <form class="form-inline my-2 my-lg-2" action="{% url 'home:search_article' %}" method="get">
                    <input class="form-control" type="text" placeholder="Search" name="keyword"
                           aria-label="Search">
                    <button class="btn btn-secondary border border-success" type="submit"><i class="fa fa-search"
                                                                                             aria-hidden="true"></i>
                    </button>
                </form>
                {% elif item == 'File' %}
                <form class="form-inline my-2 my-lg-2" action="{% url 'home:search_file' %}" method="get">
                    <input class="form-control" type="text" placeholder="Search" name="keyword"
                           aria-label="Search">
                    <button class="btn btn-secondary border border-success" type="submit"><i class="fa fa-search"
                                                                                             aria-hidden="true"></i>
                    </button>
                </form>
                {% else %}
                <form class="form-inline my-2 my-lg-2" action="{% url 'home:search_link' %}" method="get">
                    <input class="form-control" type="text" placeholder="Search" name="keyword"
                           aria-label="Search">
                    <button class="btn btn-secondary border border-success" type="submit"><i class="fa fa-search"
                                                                                             aria-hidden="true"></i>
                    </button>
                </form>
                {% endif %}
            </div>
            {% if item == 'Article' %}
            <form action="{% url 'post:article' %}">
                <button type="submit" class="btn btn-outline-success btn-add-article" style="float: right">
                    ADD {{ item }}&nbsp;<i class="fa fa-plus" aria-hidden="true"></i>
                </button>
            </form>
            {% elif item == 'File' %}
            <form action="{% url 'post:file' %}">
                <button type="submit" class="btn btn-outline-success btn-add-article" style="float: right">
                    ADD {{ item }}&nbsp;<i class="fa fa-plus" aria-hidden="true"></i>
                </button>
            </form>
            {% else %}
            <form action="{% url 'post:link' %}">
                <button type="submit" class="btn btn-outline-success btn-add-article" style="float: right">
                    ADD {{ item }}&nbsp;<i class="fa fa-plus" aria-hidden="true"></i>
                </button>
            </form>
            {% endif %}
        </div>
        <table class="table table-striped table-sm table-bordered table-hover" style="text-align: center;width: 100%;">
            <thead class="thead-dark">
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Operation</th>
            </tr>
            </thead>
            {% for item in page %}
            <tr>
                {% if item.title %}
                <td>{{ item.title }}</td>
                <td>{{ item.category.title }}</td>
                <td style="width: 13%;">
                    <a href="{% url 'main:articleview' item.id %}" style="margin-right: 20px;color: yellowgreen;">
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    </a>
                    <a href="{% url 'home:edit_article' item.id %}" style="margin-right: 20px;">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                    <a style="color: red;">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                </td>
                {% elif item.path %}
                <td>{{ item.name }}</td>
                <td>{{ item.description }}</td>
                <td style="width: 13%;">
                    <a href="/{{ item.path }}" style="margin-right: 20px;">
                        <i class="fa fa-download" aria-hidden="true"></i>
                    </a>
                    <a style="color: red;"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                </td>
                {% else %}
                <td>{{ item.name }}</td>
                <td>{{ item.description }}</td>
                <td style="width: 13%;">
                    <a href="{{ item.url }}" style="margin-right: 20px;color: yellowgreen;">
                        <i class="fa fa-external-link" aria-hidden="true"></i>
                    </a>
                    <a href="{% url 'home:edit_link' item.id %}" style="margin-right: 20px;">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                    <a style="color: red;"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
        <!-------------------------------------分页------------------------------------------->
        <div class="container" style="width: 75%;margin: 0;padding: 0px">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link" href='?page=1'>First</a>
                    </li>
                    {% if page.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?keyword={{ keyword }}&page={{ page.previous_page_number }}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% else %}
                    {% endif %}
                    {% for num in page_range %}
                    {% if num == page.number %}
                    <li class="page-item">
                        <a class="page-link" href="#" style="color: red;">{{ num }}</a>
                    </li>
                    {% elif num == "..." %}
                    <li><i class="page-link">{{ num }}</i></li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    {% if page.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?keyword={{ keyword }}&page={{ page.next_page_number }}"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link" href="?keyword={{ keyword }}&page={{ paginator.num_pages }}">Last</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <!---->

    <div class="item item-3">
        <div style="text-align: center;">
            <img class="rounded-circle portrait" src="{{ profile.portrait.url }}" alt="None">
        </div>
        <hr/>
        <div class="info">
            <span>Username:&nbsp;{{ request.user.username }}</span>
        </div>
        <div class="info">
            <span>Gender:&nbsp;{{ profile.gender }}</span>
        </div>
        <div class="info">
            <span>Nickname:&nbsp;{{ profile.nickname }}</span>
        </div>
        <div class="info">
            <span>Email:&nbsp;{{ request.user.email }}</span>
        </div>
        <div class="info">
            <span><i class="fa fa-phone" aria-hidden="true"></i>&nbsp;Phone:&nbsp;{{ profile.phone }}</span>
        </div>
        <div class="info">
            <span style="display: block">Resume:&nbsp;</span>
            <textarea style="width: 100%;min-height: 200px;font-size: 1rem">{{ profile.resume }}</textarea>
        </div>
        <div class="info" style="text-align: center">
            <form action="{% url 'home:profile' profile.id %}">
                <button type="submit" class="btn btn-outline-primary" style="width: 80%">
                    <b>Edit&nbsp;<i class="fa fa-pencil" aria-hidden="true"></i></b>
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/home/center_for_visitor.html
{% extends 'main/footer.html' %}
{% load static %}

{% block title %} User center {% endblock title %}

<!---------------------------静态资源----------------------------->

{% block link %}
<link href="{% static 'home/css/center.css' %}" rel="stylesheet"/>
{% endblock link %}

{% block content %}
<div class="container-layne">
    <div class="item item-1">
        <div class="upload">
            <a href="{% url 'main:visitarticleview' profile_for_visitor.user.id %}">
                <span>Articles</span>&nbsp;<i class="fa fa-file-text" aria-hidden="true"></i>
            </a>
        </div>
        <hr/>
        <div class="upload">
            <a href="{% url 'main:visitfileview' profile_for_visitor.user.id %}">
                <span>Files</span>&nbsp;<i class="fa fa-file-archive-o" aria-hidden="true"></i>
            </a>
        </div>
        <hr/>
        <div class="upload">
            <a href="{% url 'main:visitlinkview' profile_for_visitor.user.id %}">
                <span>Links</span>&nbsp;<i class="fa fa-link" aria-hidden="true"></i>
            </a>
        </div>
        <hr/>
    </div>

    <!---变化的部分--->
    <div class="item item-2 table-responsive">
        <div class="sub-nav">
            <div style="display: inline;float: left;">
                {% if item == 'Article' %}
                <form class="form-inline my-2 my-lg-2" action="{% url 'main:visitsearcharticleview' profile_for_visitor.user.id %}" method="get">
                    <input class="form-control" type="text" placeholder="Search" name="keyword"
                           aria-label="Search">
                    <button class="btn btn-secondary border border-success" type="submit"><i class="fa fa-search"
                                                                                             aria-hidden="true"></i>
                    </button>
                </form>
                {% elif item == 'File' %}
                <form class="form-inline my-2 my-lg-2" action="{% url 'main:visitsearchfileview' profile_for_visitor.user.id %}" method="get">
                    <input class="form-control" type="text" placeholder="Search" name="keyword"
                           aria-label="Search">
                    <button class="btn btn-secondary border border-success" type="submit"><i class="fa fa-search"
                                                                                             aria-hidden="true"></i>
                    </button>
                </form>
                {% else %}
                <form class="form-inline my-2 my-lg-2" action="{% url 'main:visitsearchlinkview' profile_for_visitor.user.id %}" method="get">
                    <input class="form-control" type="text" placeholder="Search" name="keyword"
                           aria-label="Search">
                    <button class="btn btn-secondary border border-success" type="submit"><i class="fa fa-search"
                                                                                             aria-hidden="true"></i>
                    </button>
                </form>
                {% endif %}
            </div>
        </div>
        <table class="table table-striped table-sm table-bordered table-hover" style="text-align: center;width: 100%;">
            <thead class="thead-dark">
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Operation</th>
            </tr>
            </thead>
            {% for item in page %}
            <tr>
                {% if item.title %}
                <td>{{ item.title }}</td>
                <td>{{ item.category.title }}</td>
                <td style="width: 13%;">
                    <a href="{% url 'main:articleview' item.id %}" style="margin-right: 20px;color: yellowgreen;">
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    </a>
                    <a href="" style="margin-right: 20px;color: lightgrey">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                    <a style="color: lightgrey;">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                </td>
                {% elif item.path %}
                <td>{{ item.name }}</td>
                <td>{{ item.description }}</td>
                <td style="width: 13%;">
                    <a href="/{{ item.path }}" style="margin-right: 20px;">
                        <i class="fa fa-download" aria-hidden="true"></i>
                    </a>
                    <a style="color: lightgrey;"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                </td>
                {% else %}
                <td>{{ item.name }}</td>
                <td>{{ item.description }}</td>
                <td style="width: 13%;">
                    <a href="{{ item.url }}" style="margin-right: 20px;color: yellowgreen;">
                        <i class="fa fa-external-link" aria-hidden="true"></i>
                    </a>
                    <a href="" style="margin-right: 20px;color: lightgrey;">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                    <a style="color: lightgrey;"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
        <!-------------------------------------分页------------------------------------------->
        <div class="container" style="width: 75%;margin: 0;padding: 0px">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link" href='?page=1'>First</a>
                    </li>
                    {% if page.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?keyword={{ keyword }}&page={{ page.previous_page_number }}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% else %}
                    {% endif %}
                    {% for num in page_range %}
                    {% if num == page.number %}
                    <li class="page-item">
                        <a class="page-link" href="#" style="color: red;">{{ num }}</a>
                    </li>
                    {% elif num == "..." %}
                    <li><i class="page-link">{{ num }}</i></li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    {% if page.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?keyword={{ keyword }}&page={{ page.next_page_number }}"
                           aria-label="Next"><span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link" href="?keyword={{ keyword }}&page={{ paginator.num_pages }}">Last</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <!---->

    <div class="item item-3">
        <div style="text-align: center;">
            <img class="rounded-circle portrait" src="{{ profile_for_visitor.portrait.url }}" alt="None">
        </div>
        <hr/>
        <div class="info">
            <span>Username:&nbsp;{{ username }}</span>
        </div>
        <div class="info">
            <span>Gender:&nbsp;{{ profile_for_visitor.gender }}</span>
        </div>
        <div class="info">
            <span>Nickname:&nbsp;{{ profile_for_visitor.nickname }}</span>
        </div>
        <div class="info">
            <span><i class="fa fa-phone" aria-hidden="true"></i>&nbsp;Phone:&nbsp;{{ profile_for_visitor.phone }}</span>
        </div>
        <div class="info">
            <span style="display: block">Resume:&nbsp;</span>
            <textarea style="width: 100%;min-height: 200px;font-size: 1rem">{{ profile_for_visitor.resume }}</textarea>
        </div>
    </div>
</div>
{% endblock content %}

templates/home/edit_link.html
{% extends 'usebootstrap.html' %}
{% load static %}

{% block title %} Edit your Link {% endblock title %}

{% block content %}
<div style="width:80%;padding:20px;" class="container">
    <div class="col">
        <form enctype="multipart/form-data" action="{% url 'home:edit_link' link.id %}" method="post" novalidate>
            {% csrf_token %}

            {% if good_message %}
            <div class="alert alert-success">{{ good_message }}</div>
            {% elif bad_message %}
            <div class="alert alert-danger">{{ bad_message }}</div>
            {% endif %}

            <h3 style="padding-bottom:20px;">Edit Your Link</h3>

            <div class="form-group" style="color:black; background-color: ;">
                {{ form.name.label_tag }}
                <input type="text" class="form-control" name="name" value="{{ link.name }}">
                {% if form.name.errors %}
                <div class="alert alert-danger" style="margin: 5px;padding 0px;">{{ form.name.errors }}</div>
                {% endif %}
            </div>

            <div class="form-group" style="color:black;">
                {{ form.url.label_tag }}
                <input type="text" class="form-control" name="url" value="{{ link.url }}">
                {% if form.url.errors %}
                <div class="alert alert-danger" style="margin: 5px;padding 0px;">{{ form.url.errors }}</div>
                {% endif %}
            </div>

            <div class="form-group" style="color:black;">
                {{ form.description.label_tag }}
                <input type="text" class="form-control" name="description" value="{{ link.description }}">
                {% if form.note.errors %}
                <div class="alert alert-danger" style="margin: 5px;padding 0px;">{{ form.description.errors }}</div>
                {% endif %}
            </div>

            <div style="margin-top: 20px;">
                <a href="{% url 'home:center' %}">
                    <ins>Back</ins>
                </a>
                <button type="submit" class="btn btn-success float-right" style="width: 15%;">Post</button>
            </div>
        </form>
    </div>
</div>

{% endblock content%}