alpha/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('captcha/', include('captcha.urls')),  # 图形验证码功能。要在主项目下添加。
                  path('mdeditor/', include('mdeditor.urls')),  # 为实现markdown功能，不清楚有啥异常
                  re_path(r'^$', include(('login.urls', 'login'), namespace='empty')),      # 命名一定不能重复
                  re_path(r'^login/', include(('login.urls', 'login'), namespace='login')),  # 将路由分发给下面的app处理
                  re_path(r'^home/', include(('home.urls', 'home'), namespace='home')),
                  re_path(r'^post/', include(('post.urls', 'post'), namespace='post')),
                  re_path(r'^main/', include(('main.urls', 'main'), namespace='main')),
                  re_path(r'^introduction/', include(('introduction.urls', 'introduction'), namespace='introduction')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加上这句至关重要，不然照片不显示

if settings.DEBUG:  # 添加媒体文件url,生产环境下使用
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

campus/main/urls.py
from django.urls import path, re_path
from . import views

# 正在部署的应用的名称，Django2.0之后，app的urls.py必须配置app_name，否则会报错。
app_name = 'main'

urlpatterns = [
    re_path('^$', views.empty),  # 正则匹配必须用re_path
    re_path('^index', views.IndexView.as_view(), name='indexview'),
    re_path('^categories', views.CategoryView.as_view(), name='categoryview'),
    re_path('^articles/(?P<id>.*)', views.ArticleView.as_view(), name='articleview'),
    re_path('^files', views.FileListView.as_view(), name='filelistview'),
    re_path('^links', views.LinkListView.as_view(), name='linklistview'),
    re_path('^search$', views.SearchView.as_view(), name='search'),
    re_path('^filelist/search$', views.SearchFileListView.as_view(), name='searchfilelistview'),
    re_path('^linklist/search$', views.SearchLinkListView.as_view(), name='searchlinklistview'),
    re_path('^visit/(?P<id>.*)/article$', views.VisitArticleView.as_view(), name='visitarticleview'),
    re_path('^visit/(?P<id>.*)/file$', views.VisitFileView.as_view(), name='visitfileview'),
    re_path('^visit/(?P<id>.*)/link$', views.VisitLinkView.as_view(), name='visitlinkview'),
    re_path('^visit/(?P<id>.*)/article/search$', views.VisitSearchArticleView.as_view(), name='visitsearcharticleview'),
    re_path('^visit/(?P<id>.*)/file/search$', views.VisitSearchFileView.as_view(), name='visitsearchfileview'),
    re_path('^visit/(?P<id>.*)/link/search$', views.VisitSearchLinkView.as_view(), name='visitsearchlinkview'),
    re_path('^logout', views.logout, name='logout'),
]

campus/post/urls.py
from django.urls import path, re_path
from . import views

# 正在部署的应用的名称，Django2.0之后，app的urls.py必须配置app_name，否则会报错。
app_name = 'post'

urlpatterns = [
    re_path('^$', views.empty),  # 正则匹配必须用re_path
    re_path('^post', views.post),
    re_path('^article', views.PostArticleView.as_view(), name='article'),
    re_path('^file', views.PostFileView.as_view(), name='file'),
    re_path('^link', views.PostLinkView.as_view(), name='link'),
]

campus/main/models.py
from django.db import models
from django.utils import timezone
from mdeditor.fields import MDTextField
from login import models as login_models
from django.contrib.auth.models import User


class MainCategory(models.Model):
    # 主分类，例如Python基础学习，属于python主分类
    title = models.CharField(max_length=100, blank=True)
    # 分类的创建时间
    created = models.DateTimeField(default=timezone.now())
    # 创建人员
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='admin')

    # admin站点信息 调试查看对象
    def __str__(self):
        return self.title

    class Meta:
        ordering = ["created"]


class SubCategory(models.Model):
    # 文章分类
    # 分类标题
    title = models.CharField(max_length=100, blank=True)
    # 分类的创建时间
    created = models.DateTimeField(default=timezone.now())
    # 主分类
    category = models.ForeignKey(
        MainCategory,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='category',
        default='1',
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='admin')

    # admin站点信息 调试查看对象
    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-created"]
        # db_table = 'tb_category'  # 修改表名
        # # verbose_name = '类别管理',
        # verbose_name_plural = verbose_name


# 博客文章
class Article(models.Model):
    # 文章作者。参数on_delete 用于指定数据删除的方式，避免两个关联表数据不一致
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='admin')
    # 文章标题
    title = models.CharField(max_length=100, blank=False)
    # 文章标题图
    avatar = models.ImageField(upload_to='article/%Y%m%d/', default='article/default.jpg',
                               verbose_name='avatar', blank=True)
    # upload_to指定图片上传的路径，不存在则自动创建
    # blank,设置为True时，字段可以为空。设置为False时，字段是必须填写的
    # 文章标签
    tag = models.CharField(max_length=200, blank=False)
    # 概要
    summary = models.CharField(max_length=200, blank=False)
    # 浏览次数
    views = models.PositiveIntegerField('views', default=0)
    # 文章正文
    body = MDTextField()
    created = models.DateTimeField('created', auto_now_add=True)  # 字段在实例第一次保存的时候会保存当前时间，不管你在这里是否对其赋值
    # 文章更新时间 参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)  # 字段保存时会自动保存当前时间，但要注意每次对其实例执行save()的时候都会将当前时间保存
    # 文章分类，使用外键
    category = models.ForeignKey(
        SubCategory,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='subcategory',
        default='1',
    )

    # 内部类class Meta用于给model定义元数据
    class Meta:
        # ’-created‘ 表明数据应该以倒叙排列
        ordering = ["-created"]   # 指定模型返回的数据的排列顺序
        # db_table = 'tb_article'
        # verbose_name = ''
        # verbose_name_plural = verbose_name
        # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
        # 它最常见的就是在Django管理后台中做为对象的显示值。因此应该总是为 __str__ 返回一个友好易读的字符串

    def __str__(self):
        # 将文章标题返回
        return self.title


# 文件模型
class File(models.Model):
    # 所关联的文章名称，利用文章名称作为外键
    article = models.ForeignKey(Article, on_delete=models.CASCADE, default='2', blank=True)
    # 上传作者
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='admin')
    # 文件名称
    name = models.CharField(max_length=200)
    # 文件保存路径
    path = models.CharField(max_length=100)
    # 介绍
    description = models.CharField(max_length=200, default='the author is lazy, didn\'t give any information')
    # 上传时间
    upload_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-upload_time"]


# 链接模型
class Link(models.Model):
    # 链接名
    name = models.CharField(max_length=200)
    # 链接地址
    url = models.URLField(max_length=200, default=None)
    # 介绍
    description = models.CharField(max_length=200, default='the author is lazy, didn\'t give any introduction')
    # 上传作者
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='admin')
    # 上传时间
    upload_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        # 将文章标题返回
        return self.name

    class Meta:
        ordering = ["-upload_time"]

campus/main/views.py
from django.shortcuts import redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth import logout as sys_logout
from django.views import View
from django.views.generic import ListView, DetailView
from . import models
from login import models as login_models
from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger
import markdown
from django.contrib.auth.models import User


def empty(request):
    return redirect("main:indexview")


@login_required(login_url="login:login")
def logout(request):
    sys_logout(request)
    return redirect('login:login')


class NavView(View):
    def __init__(self):
        super().__init__()
        self.maincategory = models.MainCategory.objects.all()
        self.subcategory = models.SubCategory.objects.all()
        self.articles = models.Article.objects.all()

    def get_login_profile(self):
        profile = login_models.Profile.objects.get(user_id=self.request.user.id)
        return profile

    def get_user_data(self):
        user_article_count = models.Article.objects.filter(author_id=self.request.user.id).count()
        user_file_count = models.File.objects.filter(author_id=self.request.user.id).count()
        user_link_count = models.Link.objects.filter(author_id=self.request.user.id).count()
        return user_article_count, user_file_count, user_link_count

    def get_page(self, items, set_num):
        page_num = self.request.GET.get('page', 1)  # 使用request.GET.get()函数获取uri中的page参数的数值
        paginator = Paginator(items, set_num)  # 设置一页显示多少条数据（articles为要分页的数据）
        page_range = list(range(max(int(page_num) - 2, 1), int(page_num))) + list(
            range(int(page_num), min(int(page_num) + 2, paginator.num_pages) + 1))
        # 加上省略页码标记
        if page_range[0] - 1 >= 2:
            page_range.insert(0, '...')
        if paginator.num_pages - page_range[-1] >= 2:
            page_range.append('...')
        # 加上首页和尾页
        if page_range[0] != 1:
            page_range.insert(0, 1)
        if page_range[-1] != paginator.num_pages:
            page_range.append(paginator.num_pages)
        try:
            page = paginator.page(page_num)  # 获取当前页码的记录
        except PageNotAnInteger:  # 如果用户输入的页码不是整数时,显示第1页的内容
            page = paginator.page(1)
        except (EmptyPage, InvalidPage):  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容
            page = paginator.page(paginator.num_pages)
        return page, paginator, page_range


@method_decorator(login_required(login_url="login:login"), name='dispatch')
# 将装饰器装饰到dispatch方法上，就相当于将装饰器装饰到该class的所有方法上
class IndexView(NavView, ListView):
    # 模板位置
    template_name = 'main/index.html'

    # 加上这一行，告知允许哪种请求方式
    # http_method_names = ['GET', 'POST']

    def get_queryset(self):  # 重写get_queryset方法
        recommend = models.Article.objects.all().order_by('-views')[:8]
        link_list = models.Link.objects.all().order_by('-upload_time')[:12]
        file_list = models.File.objects.all().order_by('-upload_time')[:7]  # 获取最新的文件
        latest = models.Article.objects.all().order_by('-created')[:8]
        return locals()

    def get_context_data(self, **kwargs):  # 重写get_context_data方法
        # 很关键，必须把原方法的结果拿到
        context = super().get_context_data(**kwargs)
        context['maincategory'] = self.maincategory
        context['subcategory'] = self.subcategory
        context['profile'] = self.get_login_profile()
        context['recommend'] = self.get_queryset().get('recommend')
        context['link_list'] = self.get_queryset().get('link_list')
        context['file_list'] = self.get_queryset().get('file_list')  # 获取最新的文件
        context['latest'] = self.get_queryset().get('latest')
        context['user_article_count'] = self.get_user_data()[0]
        context['user_file_count'] = self.get_user_data()[1]
        context['user_link_count'] = self.get_user_data()[2]
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class CategoryView(IndexView):
    # 模板位置
    template_name = 'main/category.html'
    pk_url_kwarg = 'category_id'
    model = models.Article

    def get_queryset(self):  # 重写get_queryset方法
        self.articles = self.model.objects.filter(category=self.request.GET.get('category', 7))
        cat_id = self.request.GET.get('category', 1)
        page, paginator, page_range = self.get_page(self.articles, 10)
        return locals()

    # 重写get_context_data方法
    def get_context_data(self, **kwargs):
        # 很关键，必须把原方法的上下文结果拿到
        context = super().get_context_data(**kwargs)
        context['cat_id'] = self.get_queryset().get('cat_id')
        context['page'] = self.get_queryset().get('page')
        context['paginator'] = self.get_queryset().get('paginator')
        context['page_range'] = self.get_queryset().get('page_range')
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class ArticleView(NavView, DetailView):
    # 模板位置
    model = models.Article
    template_name = "main/article.html"
    context_object_name = "article"
    pk_url_kwarg = 'id'

    def get_object(self, queryset=None):
        """
        获取需要展示的对象
        """
        # 首先调用父类的方法
        article = super(ArticleView, self).get_object()
        md = markdown.Markdown(
            extensions=[
                # 包含 缩写、表格等常用扩展
                'markdown.extensions.extra',
                # 语法高亮扩展
                'markdown.extensions.codehilite',
                # 目录扩展
                'markdown.extensions.toc',
                'markdown.extensions.tables',
            ]
        )
        article.body = md.convert(article.body)
        # 浏览量 +1
        article.views = article.views + 1
        article.save(update_fields=['views'])
        return article

    # 重写get_context_data方法
    def get_context_data(self, **kwargs):
        # 很关键，必须把原方法的结果拿到
        context = super().get_context_data(**kwargs)
        context['maincategory'] = self.maincategory
        context['subcategory'] = self.subcategory
        context['profile'] = self.get_login_profile()
        context['files'] = models.File.objects.filter(article_id=self.get_object().id)
        # 获取当前文章的上一篇和下一篇
        context['previous_article'] = models.Article.objects.filter(id__gt=self.get_object().id,
                                                                    category=self.get_object().category.id).last()
        context['next_article'] = models.Article.objects.filter(id__lt=self.get_object().id,
                                                                category=self.get_object().category.id).first()
        context['user_article_count'] = self.get_user_data()[0]
        context['user_file_count'] = self.get_user_data()[1]
        context['user_link_count'] = self.get_user_data()[2]
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class VisitArticleView(NavView, DetailView):
    # 模板位置
    model = User
    template_name = "home/center_for_visitor.html"
    context_object_name = "profile_for_visitor"
    pk_url_kwarg = 'id'

    def get_object(self, queryset=None):
        """
        获取需要展示的对象
        """
        # 首先调用父类的方法
        user = super(VisitArticleView, self).get_object()
        return user

    def get_host_data(self):  # 获取主人的资料
        articles = models.Article.objects.filter(author_id=self.get_object().id)
        page, paginator, page_range = self.get_page(articles, 10)
        return locals()

    # 重写get_context_data方法
    def get_context_data(self, **kwargs):
        # 很关键，必须把原方法的结果拿到
        context = super().get_context_data(**kwargs)
        context['maincategory'] = models.MainCategory.objects.all()
        context['subcategory'] = models.SubCategory.objects.all()
        context['profile'] = self.get_login_profile()
        context['profile_for_visitor'] = login_models.Profile.objects.get(user_id=self.get_object().id)
        context['user_article_count'] = self.get_user_data()[0]
        context['user_file_count'] = self.get_user_data()[1]
        context['user_link_count'] = self.get_user_data()[2]
        context['page'] = self.get_host_data().get('page')
        context['page_range'] = self.get_host_data().get('page_range')
        context['paginator'] = self.get_host_data().get('paginator')
        context['username'] = self.get_object().username
        context['item'] = 'Article'
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class VisitFileView(VisitArticleView):
    template_name = "home/center_for_visitor.html"

    def get_host_data(self):  # 获取主人的资料
        file_list = models.File.objects.filter(author_id=self.get_object().id)
        page, paginator, page_range = self.get_page(file_list, 10)
        return locals()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['item'] = 'File'
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class VisitLinkView(VisitArticleView):
    template_name = "home/center_for_visitor.html"

    def get_host_data(self):  # 获取主人的资料
        link_list = models.Link.objects.filter(author_id=self.get_object().id)
        page, paginator, page_range = self.get_page(link_list, 10)
        return locals()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['item'] = 'Link'
        return context


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class VisitSearchArticleView(VisitArticleView):

    def get_host_data(self):  # 获取主人的资料
        self.articles = models.Article.objects.filter(author_id=self.get_object().id)
        keyword = self.request.GET.get('keyword')
        if keyword:  # 获取搜索的关键词

templates/main/footer.html
{% extends 'main/nav.html' %}

<!---------------------------页面标题----------------------------->

{% block title %}
footer
{% endblock title %}

<!----------------------------页面内容---------------------------->

{% block footer %} {# 输入父模板的接口名字 #}
<footer class="footer mt-auto py-3" style="margin: 0 auto;">
    <div class="container">
        <span class="text-muted"><i class="fa fa-copyright" aria-hidden="true"></i>Copyright @layne</span>
    </div>
</footer>
{% endblock footer %}

templates/main/index.html
{% extends 'main/footer.html' %}
{% load static %}

<!---------------------------页面标题----------------------------->

{% block title %}
Welcome to FAQ Platform!
{% endblock %}

<!---------------------------静态资源----------------------------->

{% block link %}
<link href="{% static 'main/css/main-index.css' %}" rel="stylesheet"/>
{% endblock link %}

<!----------------------------页面内容---------------------------->


{% block content %} {# 输入父模板的接口名字 #}
<!-- content，文章列表部分 -->
<div class="map">
    <!--推荐栏目-->
    <div class="border border-primary card shadow recommend">
        <div class="card-header">
            <b>Recommends</b>
        </div>
        <div class="card-body card-body-recommend">
            {% for i in recommend %}
            <div class="card shadow bg-light border border-white card-small">
                <!--文章标题图-->
                <img class="card-img-top rounded" src="{{ i.avatar.url }}" alt="Card image cap">
                <!--文章文字内容-->
                <div class="card-bod card-body-small">
                    <!--文章标题-->
                    <div class="card-title card-title-recommend-small">
                        <a href="{% url 'main:articleview' i.id %}">{{ i.title }}</a>
                    </div>
                    <!--文章类目-->
                    <div class="article-category-recommend"><!--上下2，左右5-->
                        <a class="badge badge-info" href="{% url 'main:categoryview' %}/?category={{ i.category.id }}">
                            {{ i.category.title }}
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <!--最近更新栏目-->
    <div class="border border-success card shadow latest">
        <div class="card-header">
            <b>Latest Uploads</b>
        </div>
        <div class="card-body card-body-latest">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <!--活跃-->
                    <div class="carousel-item active">
                        <img class="d-block w-40 image-latest" src="{{ latest.0.avatar.url }}">
                        <div>
                            <div class="card-title-latest">
                                <a href="{% url 'main:articleview' latest.0.id %}">{{ latest.0.title }}</a>
                            </div>
                            <p class="card-text overflow-auto summary-latest">{{ latest.0.summary }}</p>
                        </div>
                        <!--文章类目-->
                        <div class="category-latest"><!--上下2，左右5-->
                            <a class="badge badge-info"
                               href="{% url 'main:categoryview' %}/?category={{ latest.0.category.id }}">
                                {{ latest.0.category.title }}
                            </a>
                        </div>
                    </div>
                    {% for i in latest %}
                    {% if forloop.first %} {# 如果是第一个，那就跳过，避免重复 #}
                    {% else %}
                    <!--其他-->
                    <div class="carousel-item">
                        <img class="d-block w-40 image-latest" src="{{ i.avatar.url }}">
                        <div>
                            <div class="card-title-latest">
                                <a href="{% url 'main:articleview' i.id %}">{{ i.title }}</a>
                            </div>
                            <p class="card-text overflow-auto summary-latest">{{ i.summary }}</p>
                        </div>
                        <!--文章类目-->
                        <div class="category-latest"><!--上下2，左右5-->
                            <a class="badge badge-info"
                               href="{% url 'main:categoryview' %}/?category={{ i.category.id }}">
                                {{ i.category.title }}
                            </a>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <!--下载栏目-->
    <div class="border border-danger card shadow download">
        <div class="card-header">
            <div style="float: left"><b>Downloads</b></div>
            <div style="float: right">
                <a href="{% url 'main:filelistview' %}" style="color: grey">
                    <i class="fa fa-hand-o-right" aria-hidden="true"></i>&nbsp;More>>>
                </a>
            </div>
        </div>
        <div class="card-body">
            <ul class="list-group">
                {% for i in file_list %}
                <li class="list-group-item" style="padding: 10px;">
                    <div style="float: left">
                        {{ i.name }}
                    </div>
                    <div style="float: right;margin-right: 20px;">
                        <a href="/{{ i.path }}"><i class="fa fa-download" aria-hidden="true"></i></a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <!--链接栏目-->
    <div class="border border-warning card shadow link">
        <div class="card-header">
            <div style="float: left"><b>Links</b></div>
            <div style="float: right">
                <a href="{% url 'main:linklistview' %}" style="color: grey">
                    <i class="fa fa-hand-o-right" aria-hidden="true"></i>&nbsp;More>>>
                </a>
            </div>
        </div>
        <div class="card-body">
            {% for i in link_list %}
            <i style="margin-top: 5px;">
                <a href="{{ i.url }}">{{ i.name }}</a>
            </i><br/>
            {% endfor %}
        </div>
    </div>
</div>
<br>

{% endblock %}

templates/main/nav.html
{% extends 'usebootstrap.html' %}
{% load static %}

{% block title %} nav {% endblock title %}

{% block nav %}
<!--导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark" style="z-index: 1111"> <!--z-index设置模态框层级，不然被遮盖-->
    <a class="navbar-brand" href="{% url 'main:indexview' %}">HOME</a>
    <!-- 导航栏，文章分类部分-->
    <ul class="nav">
        {% for mcat in maincategory %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="" role="button" aria-haspopup="true"
               aria-expanded="false">{{ mcat.title }}</a>
            <div class="dropdown-menu">
                {% for scat in subcategory %}
                {% if scat.category == mcat %}
                <a class="dropdown-item" href="{% url 'main:categoryview' %}/?category={{ scat.id }}">
                    {{ scat.title }}
                </a>
                {% endif %}
                {% endfor %}
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="col order-last">
        <div id="search_tool">
            <!--搜索框-->
            <form class="form-inline my-2 my-lg-0" action="{% url 'main:search' %}" method="get">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="text" value="{{ keyword }}" placeholder="Search"
                       name="keyword" aria-label="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        <div class="dropdown layne-dropdown">
            <!--小头像照片-->
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false">
                <img class="rounded-circle layne-portrait-small" src="{{ profile.portrait.url }}" alt="None">
            </a>
            <!--用户下拉框-->
            <div class="dropdown-menu dropdown-menu-right" id="layne-dropdown-menu" aria-labelledby="dropdownMenuLink">
                <!--以容器形式展现-->
                <div style="margin-top: 10px;">
                    <div style="text-align: center;">
                        <img class="rounded-circle" src="{{ profile.portrait.url }}" alt="None"
                             style="width: 60px;height: 60px;">
                    </div>
                    <div style="text-align: center;line-height: 36px;font-size: 1.5rem;">
                        <span>Hello, {{ request.user.username }}</span>
                    </div>
                </div>
                <hr>
                <div style="display: flex;">
                    <div class="text-center layne-dropdown-menu-grid">
                        <a href="{% url 'post:article' %}">
                            <i class="fa fa-pencil-square-o layne-fa" aria-hidden="true"></i>
                        </a>
                        <div class="text-center">post articles ({{ user_article_count }})</div>
                    </div>
                    <div class="text-center layne-dropdown-menu-grid">
                        <a href="{% url 'post:file' %}">
                            <i class="fa fa-file-archive-o layne-fa" aria-hidden="true"></i>
                        </a>
                        <div class="text-center">post files ({{ user_file_count }})</div>
                    </div>
                    <div class="text-center layne-dropdown-menu-grid">
                        <a href="{% url 'post:link' %}">
                            <i class="fa fa-link layne-fa" aria-hidden="true"></i>
                        </a>
                        <div class="text-center">post links ({{ user_link_count }})</div>
                    </div>
                </div>
                <div style="display: flex">
                    <div class="text-center layne-dropdown-menu-grid">
                        <a href="{% url 'home:center' %}">
                            <i class="fa fa-user-circle layne-fa" aria-hidden="true"></i>
                        </a>
                        <div class="text-center">account</div>
                    </div>
                    <div class="text-center layne-dropdown-menu-grid">
                        <a href="/media/help.html"><i class="fa fa-question-circle-o layne-fa"
                                                      aria-hidden="true"></i></a>
                        <div class="text-center">help</div>
                    </div>
                    <div class="text-center layne-dropdown-menu-grid">
                        <a href="/admin/"><i class="fa fa-user-secret layne-fa" aria-hidden="true"></i></a>
                        <div class="text-center">management</div>
                    </div>
                </div>
                <div class="text-center">
                    <form action="{% url 'main:logout' %}">
                        <button type="button" class="border layne-dropdown-menu-exit btn btn-outline-danger"
                                data-toggle="modal" data-target="#exampleModalCenter">
                            <i class="fa fa-sign-out" style="color: black" aria-hidden="true"></i>
                            <b style="color: black">Exit</b>
                        </button>
                        <!-- Modal -->
                        <div class="modal" id="exampleModalCenter" tabindex="-1" role="dialog"
                             aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalCenterTitle"><i
                                                class="fa fa-info-circle" aria-hidden="true"></i></h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true"><i class="fa fa-times"
                                                                        aria-hidden="true"></i></span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <b>Are you sure you want to quit ? </b>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-success" data-dismiss="modal">Stay</button>
                                        <form action="{% url 'main:logout' %}">
                                            <button type="submit" class="btn btn-danger">Quit</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</nav>
<!--内容接口-->
{% endblock nav %}