alpha/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('captcha/', include('captcha.urls')),  # 图形验证码功能。要在主项目下添加。
                  path('mdeditor/', include('mdeditor.urls')),  # 为实现markdown功能，不清楚有啥异常
                  re_path(r'^$', include(('login.urls', 'login'), namespace='empty')),      # 命名一定不能重复
                  re_path(r'^login/', include(('login.urls', 'login'), namespace='login')),  # 将路由分发给下面的app处理
                  re_path(r'^home/', include(('home.urls', 'home'), namespace='home')),
                  re_path(r'^post/', include(('post.urls', 'post'), namespace='post')),
                  re_path(r'^main/', include(('main.urls', 'main'), namespace='main')),
                  re_path(r'^introduction/', include(('introduction.urls', 'introduction'), namespace='introduction')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加上这句至关重要，不然照片不显示

if settings.DEBUG:  # 添加媒体文件url,生产环境下使用
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

campus/login/urls.py
from django.urls import path, re_path
from . import views

# 正在部署的应用的名称，Django2.0之后，app的urls.py必须配置app_name，否则会报错。
app_name = 'login'

urlpatterns = [
    re_path('^$', views.empty, name='empty'),  # 正则匹配必须用re_path
    re_path('^login$', views.LoginView.as_view(), name='login'),
    re_path('^register$', views.RegisterView.as_view(), name='register'),
    re_path('^confirm$', views.confirm),
]

campus/login/models.py
from django.db import models
from django.contrib.auth.models import User


# 用户扩展信息
class Profile(models.Model):
    # 先建一个元组存储性别
    gender_type = (('male', '男'), ('female', '女'))
    # 与 User 模型构成一对一的关系
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # 性别
    gender = models.CharField(max_length=32, choices=gender_type, default="female")
    # 昵称，可选
    nickname = models.CharField(max_length=191, blank=True)
    # 电话号码字段，必填
    phone = models.CharField(max_length=20, blank=False)
    # 头像，可选，需要设置默认头像
    portrait = models.ImageField(upload_to='profile/portrait/%Y%m%d/', default='profile/portrait/default.png', blank=False)
    # 个人简介，可选
    resume = models.TextField(max_length=500, blank=True)
    # 是否已经邮件确认
    has_confirmed = models.BooleanField(default=False)
    # 创建时间
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username   # 这里与参考不一样

    class Meta:  # 元数据里定义用户按创建时间的反序排列，也就是最近的最先显示；尚未搞明白
        ordering = ["-c_time"]
        verbose_name = "user"
        verbose_name_plural = "users"


class ConfirmString(models.Model):  # 创建新的表格来装数据
    code = models.CharField(max_length=256)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    c_time = models.DateTimeField(auto_now_add=True)    # 字段在实例第一次保存的时候会保存当前时间，不管你在这里是否对其赋值

    def __str__(self):
        return self.user.name + ":   " + self.code

    class Meta:
        ordering = ["-c_time"]
        verbose_name = "confirm code"
        verbose_name_plural = "confirm codes"

campus/login/forms.py
from django import forms
from captcha.fields import CaptchaField  # 图形验证码
from django.forms import widgets
from . import models


class UserLoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=128, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "Username", 'autofocus': 'required'}))
    password = forms.CharField(label="Password", max_length=512,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': "Password"}))
    captcha = CaptchaField(label='Code', )  # 验证码图片和输入框是一个整体，无法设置样式！！！

    def clean_username(self):
        username = self.cleaned_data.get('username')
        filter_result = models.User.objects.filter(username__exact=username)
        if not filter_result:
            raise forms.ValidationError('Username not exist!')
        return username


class UserRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password = forms.CharField(label="Password", max_length=512,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': "Password"}))
    confirm_password = forms.CharField(label="Confirm Password", max_length=512,
                                       widget=forms.PasswordInput(
                                           attrs={'class': 'form-control', 'placeholder': "Confirm Your Password"}))

    class Meta:
        model = models.User
        fields = ('username', 'email', 'password', 'confirm_password')
        # fields = ('nickname', 'password', 'password2', 'portrait', 'phone', 'resume')
        # fields = "__all__"  # 字段，如果是__all__,就是表示列出所有的字段
        # exclude = None  # 排除的字段
        # labels = None  # 提示信息
        # help_texts = None  # 帮助提示信息
        widgets = {'username': widgets.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
                   'email': widgets.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
                   }  # 自定义插件
        # error_messages = None  # 自定义错误信息
        # error_messages用法：
        # error_messages = {
        #     'name': {'required': "用户名不能为空", },
        #     'age': {'required': "年龄不能为空", },
        # }

    # 对两次输入的密码是否一致进行检查, def clean_[字段]这种写法Django会自动调用，来对单个字段的数据进行验证清洗。
    def clean_confirm_password(self):
        data = self.cleaned_data
        if data.get('password') == data.get('confirm_password'):
            return data.get('password')
        else:
            raise forms.ValidationError("Passwords not same!")

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if len(username) < 3:
            raise forms.ValidationError("Your username must be at least 3 characters long")
        elif len(username) > 20:
            raise forms.ValidationError("Your username is too long")
        else:
            filter_result = models.User.objects.filter(username__exact=username)
            if len(filter_result) > 0:
                raise forms.ValidationError('Your username already exists')
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        filter_result = models.User.objects.filter(email__exact=email)
        if len(filter_result) > 0:
            raise forms.ValidationError("Your email already exists")
        return email

campus/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from . import forms
from . import models


def empty(request):
    return redirect('/main/')


def confirm(request):
    return HttpResponse("用户确认页面")


class GetMethodMixin:
    form_class = forms.UserLoginForm
    template_name = 'login/login.html'
    initial = {'key': 'value'}

    def get(self, request):
        form = self.form_class(initial=self.initial)
        # 已登录用户不能再次登录
        if request.user.id:
            return redirect("main:indexview")
        return render(request, self.template_name, locals())


@method_decorator(csrf_exempt, name="post")  # 装饰器name参数指明要装饰的函数名称
class LoginView(View, GetMethodMixin):  # 命名规范化，可继承复用
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():  # 判断数据是否合法，True合法
            # 用户名字符合法性验证
            # 密码长度验证
            # 更多的其它验证.....
            data = form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个 user 对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # if not user.has_confirmed:
                #     message = '该用户还未经过邮件确认！'
                #     return render(request, self.template_name, locals())
                # 将用户数据保存在 session 中，即实现了登录动作
                login(request, user)
                return redirect("main:indexview")       # 这里也可以使用url反查
            else:
                message = 'Username or password error!'
                return render(request, self.template_name, locals())
        else:
            bad_message = "Opts! something wrong"
            return render(request, self.template_name, locals())


class RegisterView(View, GetMethodMixin):  # 继承混入类，可重用一些方法
    form_class = forms.UserRegisterForm         # 重写表单
    template_name = 'login/register.html'       # 重写模板位置
    initial = {'key': 'value'}

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            # new_user = form.save(commit=False)
            # #设置密码
            # new_user.set_password(form.cleaned_data['password'])
            # 将新用户保存到数据库中
            # new_user.save()   # 如果直接使用objects.create()方法后不需要使用save()
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['confirm_password']
            new_user = models.User.objects.create_user(username=username, password=password, email=email)
            user_profile = models.Profile(user=new_user)
            user_profile.save()
            good_message = "Congratulations, registration success! please go back and login!"
            return render(request, self.template_name, locals())
        else:
            bad_message = "Opts! something wrong"
            return render(request, self.template_name, locals())

templates/login/login.html
{% extends 'usebootstrap.html' %}
{% load static %}

{% block title %} Login {% endblock title %}

{% block link %}
<link href="{% static 'login/css/login.css' %}" rel="stylesheet"/>
{% endblock link %}

{% block content %}
<div class="shadow-lg p-0 mb-0 rounded bg-light container">
    <div class="">
        <div style="float:left;width:65%;">
            <img src="/static/login/image/ac.png" style="width:100%;">
        </div>
        <div style="float:right;width:35%;">
            <form class="form-login" action="{% url 'login:login' %}" method="post">
                <p class="text-center text-title" style="font: italic 1.5rem Georgia, serif;">Surabaya FAQ Platform</p>
                {% if message %}
                <div class="alert alert-danger">{{ message }}</div>
                {% endif %}
                {% csrf_token %}
                <h5 class="text-center">Login</h5>
                {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <div style="margin: 10px;padding 5px;color: red;">{{ field.errors }}</div>
                    {% endif %}
                </div>
                {% endfor %}
                <div id="button">
                    <button type="submit" class="btn btn-primary" id="login-button">Login</button>
                </div>
                <br>
                <div class="text-center">Don't have an account?
                    <a href="{% url 'login:register' %}" class="text-success">
                        <ins>Sign up</ins>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div> <!-- /container -->
{% endblock content %}

{% block script %}
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>
<script>
    $('img.captcha').attr("title", "点击更换验证码");
    $('img.captcha').click(function() {
        $.getJSON('/captcha/refresh/',function(json) {
            // This should update your captcha image src and captcha hidden input
            console.log(json);
            $("img.captcha").attr("src",json.image_url);
            $("#id_captcha_0").val(json.key);
        });
        return false;
    });
</script>
{% endblock script %}

templates/login/register.html
{% extends 'usebootstrap.html' %}
{% load static %}

{% block title %} Register {% endblock title %}

{% block link %}
<link href="{% static 'login/css/login.css' %}" rel="stylesheet"/>
{% endblock link %}

{% block content %}
<div class="container">
    <div class="col">
        <form class="form-login form-register" action="{% url 'login:register' %}" method="post">
            {% if good_message %}
            <div class="alert alert-success">{{ good_message }}</div>
            {% elif bad_message%}
            <div class="alert alert-danger">{{ bad_message }}</div>
            {% endif %}
            {% csrf_token %}
            <h3 class="text-center">Welcome to Register!</h3>
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% if field.errors %}
                <div style="margin: 10px;padding 5px;color: red;">{{ field.errors }}</div>
                {% endif %}
            </div>
            {% endfor %}
            <div>
                <a href="{% url 'login:login' %}" class="text-success">
                    <ins>Back</ins>
                </a>
                <button type="submit" class="btn btn-primary" id="register-button">Register</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}