alpha/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('captcha/', include('captcha.urls')),  # 图形验证码功能。要在主项目下添加。
                  path('mdeditor/', include('mdeditor.urls')),  # 为实现markdown功能，不清楚有啥异常
                  re_path(r'^$', include(('login.urls', 'login'), namespace='empty')),      # 命名一定不能重复
                  re_path(r'^login/', include(('login.urls', 'login'), namespace='login')),  # 将路由分发给下面的app处理
                  re_path(r'^home/', include(('home.urls', 'home'), namespace='home')),
                  re_path(r'^post/', include(('post.urls', 'post'), namespace='post')),
                  re_path(r'^main/', include(('main.urls', 'main'), namespace='main')),
                  re_path(r'^introduction/', include(('introduction.urls', 'introduction'), namespace='introduction')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加上这句至关重要，不然照片不显示

if settings.DEBUG:  # 添加媒体文件url,生产环境下使用
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

campus/home/urls.py
from django.urls import path, re_path
from . import views

# 正在部署的应用的名称，Django2.0之后，app的urls.py必须配置app_name，否则会报错。
app_name = 'home'

urlpatterns = [
    re_path('^$', views.empty),  # 正则匹配必须用re_path
    re_path('^center$', views.CenterView.as_view(), name='center'),
    re_path('^center/file$', views.CenterFileView.as_view(), name='file'),
    re_path('^center/link$', views.CenterLinkView.as_view(), name='link'),
    re_path('^center/search/article$', views.SearchArticleView.as_view(), name='search_article'),
    re_path('^center/search/file$', views.SearchFileView.as_view(), name='search_file'),
    re_path('^center/search/link$', views.SearchLinkView.as_view(), name='search_link'),
    re_path('^center/edit/profile/(?P<pk>\d+)$', views.ProfileUpdateView.as_view(), name='profile'),
    re_path('^center/edit/article/(?P<pk>\d+)$', views.ArticleUpdateView.as_view(), name='edit_article'),
    re_path('^center/edit/link/(?P<pk>\d+)$', views.LinkUpdateView.as_view(), name='edit_link'),
    # re_path('^reset', views.reset),
]

campus/post/urls.py
from django.urls import path, re_path
from . import views

# 正在部署的应用的名称，Django2.0之后，app的urls.py必须配置app_name，否则会报错。
app_name = 'post'

urlpatterns = [
    re_path('^$', views.empty),  # 正则匹配必须用re_path
    re_path('^post', views.post),
    re_path('^article', views.PostArticleView.as_view(), name='article'),
    re_path('^file', views.PostFileView.as_view(), name='file'),
    re_path('^link', views.PostLinkView.as_view(), name='link'),
]

campus/post/models.py
from django.db import models

# Create your models here.

campus/post/forms.py
from main import models
from django import forms
from mdeditor.fields import MDTextFormField  # +


class PostArticleForm(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['category', 'title', 'avatar', 'tag', 'summary', 'body', 'file']

    avatar = forms.ImageField(required=False)  # required=Ture表示必填项。
    category = forms.ModelChoiceField(label="Category", queryset=models.SubCategory.objects.all(),
                                      widget=forms.Select(attrs={'class': 'form-control'}))
    title = forms.CharField(label="Title", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "Make more keywords!"}))
    tag = forms.CharField(label="Tag", widget=forms.TextInput(attrs={'class': 'form-control'}),
                          required=True)
    summary = forms.CharField(label="Summary", widget=forms.TextInput(attrs={'class': 'form-control'}))
    body = MDTextFormField()
    # 支持多文件上传
    file = forms.FileField(required=False, label='Please choose files',
                           widget=forms.ClearableFileInput(attrs={'multiple': True}))

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if len(title) > 100:
            raise forms.ValidationError("Your title is too long!")
        return title

    def clean_tag(self):
        tag = self.cleaned_data.get('tag')
        if len(tag) > 150:
            raise forms.ValidationError("Your tag is too long!")
        return tag

    def clean_summary(self):
        summary = self.cleaned_data.get('summary')
        if len(summary) > 150:
            raise forms.ValidationError("Your summary is too long!")
        return summary


class PostFileForm(forms.ModelForm):
    class Meta:
        model = models.File
        fields = ['description']

    description = forms.CharField(label='Description', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "ex: Firmware for visiblelight"}))
    file = forms.FileField(required=True, label='Please choose files',
                           widget=forms.ClearableFileInput(attrs={'multiple': True}))


class PostLinkForm(forms.ModelForm):
    class Meta:
        model = models.Link
        fields = ['name', 'url', 'description']

    name = forms.CharField(label='Name', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "ZKTeco official website"}))
    description = forms.CharField(label='Description', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': "ZKTeco official website"}))
    url = forms.URLField(label='URL',
                         widget=forms.URLInput(
                             attrs={'class': 'form-control', 'placeholder': "https://www.zkteco.com/en/"}))

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) > 100:
            raise forms.ValidationError("Your Link name is too long!")
        return name

campus/post/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import forms
from django.views import View
from main import models
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
import os


def empty(request):
    return redirect('post:article')


def post(request):
    pass


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class PostArticleView(View):
    form_class = forms.PostArticleForm  # 重写表单
    template_name = 'post/article.html'  # 重写模板位置
    initial = {'key': 'value'}

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, locals())

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            # 同名文章判断
            same_title_article = models.Article.objects.filter(title=form.cleaned_data.get('title'))
            if same_title_article:
                bad_message = 'Oops, The title of this article already exists!'
                return render(request, 'post/article.html', locals())
            new_article = models.Article()
            new_article.author = User.objects.get(id=request.user.id)
            new_article.title = form.cleaned_data.get('title')  # 对新文章赋值。
            if form.cleaned_data.get('avatar'):
                new_article.avatar = form.cleaned_data.get('avatar')
            new_article.tag = form.cleaned_data.get('tag')
            new_article.summary = form.cleaned_data.get('summary')  # 单词错误
            new_article.category = form.cleaned_data.get('category')
            new_article.body = form.cleaned_data.get('body')
            # 新的文章，需要先保存，才可以被文件引用为外键。
            new_article.save()
            # 遍历写入到数据库中
            for f in request.FILES.getlist('file'):
                # 写入到数据库中
                file = models.File(article=new_article, name=f.name, author=User.objects.get(id=request.user.id),
                                   path=os.path.join('./media/upload', f.name))
                file.save()
                # 写入到服务器本地
                destination = open(os.path.join("./media/upload", f.name), 'wb+')
                for chunk in f.chunks():
                    destination.write(chunk)
                destination.close()
            good_message = 'Post success! well done, Keep on the good work!'
            return render(request, 'home/edit_success.html', locals())
        else:
            bad_message = "Opts! something wrong"
            return render(request, self.template_name, locals())


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class PostFileView(View):
    form_class = forms.PostFileForm  # 重写表单
    template_name = 'post/file.html'  # 重写模板位置
    initial = {'key': 'value'}

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, locals())

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES.getlist('file')
            for file in files:
                # 写入到数据库中
                new_file = models.File(author=User.objects.get(id=request.user.id), name=file.name,
                                       path=os.path.join('./media/upload', file.name))  # 实例化新文件
                description = form.cleaned_data.get('description')
                new_file.description = description
                new_file.save()
                # 写入到服务器本地
                destination = open(os.path.join("./media/upload", file.name), 'wb+')
                for chunk in file.chunks():
                    destination.write(chunk)
                destination.close()
            good_message = 'Success!'
            return render(request, self.template_name, locals())
        else:
            bad_message = "Opts! something wrong"
            return render(request, self.template_name, locals())


@method_decorator(login_required(login_url="login:login"), name='dispatch')
class PostLinkView(View):
    form_class = forms.PostLinkForm  # 重写表单
    template_name = 'post/link.html'  # 重写模板位置
    initial = {'key': 'value'}

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, locals())

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            author = User.objects.get(id=request.user.id)
            name = form.cleaned_data.get('name')
            url = form.cleaned_data.get('url')
            description = form.cleaned_data.get('description')
            new_link = models.Link()  # 实例化新的链接
            new_link.author = author
            new_link.name = name
            new_link.url = url
            new_link.description = description
            new_link.save()
            good_message = 'Success!'
            return render(request, self.template_name, locals())
        else:
            return render(request, self.template_name, locals())

templates/post/article.html
{% extends 'usebootstrap.html' %}
{% load static %}

{% block title %} Post your Article {% endblock title %}

{% block content %}

<div style="width:80%;padding:20px;" class="container">
    <div class="col">
        <form enctype="multipart/form-data" action="{% url 'post:article' %}" method="post" novalidate>
            {% csrf_token %}

            {% if good_message %}
            <div class="alert alert-success">{{ good_message }}</div>
            {% elif bad_message %}
            <div class="alert alert-danger">{{ bad_message }}</div>
            {% endif %}

            <h3 style="padding-bottom:20px;">Post Your Article</h3>

            <div style="display: block;background-color: red;">
                <div class="form-group" style="color: black;float: left;">
                    {{ form.avatar.label_tag }}<br/>
                    {{ form.avatar }}
                </div>
                <div class="form-group" style="float: right;color: black;width: 70%;">
                    {{ form.category.label_tag }}
                    {{ form.category }}
                </div>
            </div>
            <div class="form-group" style="color:black;">
                {{ form.title.label_tag }}
                {{ form.title}}
                {% if form.title.errors %}
                <div class="alert alert-danger" style="margin: 5px;padding 0px;">{{ form.title.errors }}</div>
                {% endif %}
            </div>

            <div class="form-group" style="color:black;">
                {{ form.tag.label_tag }}
                {{ form.tag }}
                {% if form.tag.errors %}
                <div class="alert alert-danger" style="margin: 5px;padding 0px;">{{ form.tag.errors }}</div>
                {% endif %}
            </div>

            <div class="form-group" style="color:black;">
                {{ form.summary.label_tag }}
                {{ form.summary }}
                {% if form.summary.errors %}
                <div class="alert alert-danger" style="margin: 5px;padding 0px;">{{ form.summary.errors }}</div>
                {% endif %}
            </div>

            <div>
                <div>
                    {{ form.body.label_tag }}
                </div>
                <div id="editormd">
                    <textarea style="display: ;" name="body"></textarea>
                </div>
                {% if form.body.errors %}
                <div class="alert alert-danger" style="margin: 5px;padding 0px;">{{ form.body.errors }}</div>
                {% endif %}
            </div>

            <!--文件上传按钮-->
            <div class="a" style="color:black;">
                {{ form.file.label_tag }}
                {{ form.file }}
            </div>

            <div style="margin-top: 20px;">
                <a href="{% url 'home:center' %}">
                    <ins>Back</ins>
                </a>
                <button type="submit" class="btn btn-success float-right" style="width: 15%;">Post</button>
            </div>
        </form>
    </div>
</div>

{% endblock content%}

templates/post/file.html
{% extends 'usebootstrap.html' %}
{% load static %}

{% block title %} Post your Article {% endblock title %}

{% block content %}

<div style="width:80%;padding:20px;" class="container">
    <div class="col">
        <form enctype="multipart/form-data" action="{% url 'post:file' %}" method="post" novalidate>
            {% csrf_token %}
            {% if good_message %}
            <div class="alert alert-success">{{ good_message }}</div>
            {% elif bad_message %}
            <div class="alert alert-danger">{{ bad_message }}</div>
            {% endif %}
            <h3 style="padding-bottom:20px;">Post Your File</h3>
            <!--文件上传按钮-->
            {% for file in form %}
            <div class="form-group" style="color:black;">
                {{ file.label_tag}}
                {{ file }}
                {% if file.errors %}
                <div class="alert alert-danger" style="margin: 5px;padding 0px;">{{ file.errors }}</div>
                {% endif %}
            </div>
            {% endfor %}
            <div style="margin-top: 20px;">
                <a href="{% url 'home:center' %}">
                    <ins>Back</ins>
                </a>
                <button type="submit" class="btn btn-success float-right" style="width: 15%;">Post</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/post/link.html
{% extends 'usebootstrap.html' %}
{% load static %}

{% block title %} Post your Link {% endblock title %}

{% block content %}

<div style="width:80%;padding:20px;" class="container">
    <div class="col">
        <form enctype="multipart/form-data" action="{% url 'post:link' %}" method="post" novalidate>
            {% csrf_token %}
            {% if good_message %}
            <div class="alert alert-success">{{ good_message }}</div>
            {% elif bad_message %}
            <div class="alert alert-danger">{{ bad_message }}</div>
            {% endif %}
            <h3 style="padding-bottom:20px;">Post Your Link</h3>
            {% for file in form %}
            <div class="form-group" style="color:black;">
                {{ file.label_tag }}
                {{ file }}
                {% if file.errors %}
                <div class="alert alert-danger" style="margin: 5px;padding 0px;">{{ file.errors }}</div>
                {% endif %}
            </div>
            {% endfor %}
            <div style="margin-top: 20px;">
                <a href="{% url 'home:center' %}">
                    <ins>Back</ins>
                </a>
                <button type="submit" class="btn btn-success float-right" style="width: 15%;">Post</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}